baseURL: "https://www.kevingimbel.com"
languageCode: "en-us"
theme: "next"
title: "Kevin Gimbel â€” Developer"

PygmentsStyle: "native"
PygmentsUseClasses: true
PygmentsCodeFencesGuessSyntax: true
PygmentsCodeFences: true

canonifyurls:  true
enableEmoji: true

defaultContentLanguage: en
languages:
  en:
    title: "Kevin Gimbel â€” Developer"
    LanguageName: EN
    weight: 1
  de:
    title: "Kevin Gimbel - Programmierer"
    LanguageName: DE
    weight: 2
    params:
      description: |
        Full-Stack Developer interested in video games, SciFi, music, and art.
      footer:
        copyright: "Inhalte &copy; 2013 - heute <a href=\"https://kevingimbel.com/de/about\">Kevin Gimbel</a>"
        description: |
          <small>Diese Website wird mit <a href="https://gohugo.io/" title="Erfahre mehr Ã¼ber Hugo">Hugo</a> erstellt, der Quellcode ist Ã¶ffentlich auf <a href="https://github.com/kevingimbel/kevingimbel.com" title="Schaue dir den Quellcode dieser Website auf GitHub.com an">GitHub</a> verfÃ¼gbar. Gehostet wird bei <a href="https://www.netlify.com/">Netlify</a>. <a href="/de/imprint/" title="Rechtliche Informationen">Impressum</a></small>
        mastodon: |
          <small>Folge mit auf Mastodon <a rel="me" href="https://bullgit.party/@kevin">@kevin@bullgit.party</a></small>
    menu:
      main:
        - Name: "Start"
          URL: "/de/"
          Weight: 1
          Pre: ğŸ¡

        - Name: "Artikel"
          URL: "/de/archive/"
          Weight: 100
          Pre: ğŸ“°
        
        - Name: "Pixel Art"
          URL: "/de/pixelart/"
          Weight: 130
          Pre: ğŸ‘¨â€ğŸ¨

        - Name: "Ãœber mich"
          URL: "/de//about/"
          Weight: 250
          Pre: ğŸ§™â€

        - Name: "Now"
          URL: "/de/now/"
          Weight: 300
          Pre: â°

menu:
  main:
    - Name: "Home"
      URL: "/"
      Weight: 1
      Pre: ğŸ¡

    - Name: "Posts"
      URL: "/archive/"
      Weight: 100
      Pre: ğŸ“°
    
    - Name: "Pixel Art"
      URL: "/pixelart/"
      Weight: 130
      Pre: ğŸ‘¨â€ğŸ¨

    - Name: "Links"
      URL: "/link/"
      Weight: 150
      Pre: ğŸ”—

    - Name: "Projects"
      URL: "/projects/"
      Weight: 200
      Pre: ğŸ’»

    - Name: "About"
      URL: "/about/"
      Weight: 250
      Pre: ğŸ§™â€

    - Name: "Now"
      URL: "/now/"
      Weight: 300
      Pre: â°

# Set permalinks, they can be content-type based!
# Reference: http://gohugo.io/extras/permalinks/
permalinks:
  # Posts should be linked under the site-root with their title.
  post: "/:title/"
  project: "/projects/:title/"

params:
  author:
    name: "Kevin Gimbel"
    avatar: "/images/avatar-kevingimbel.jpg"
  description: |
    Full-Stack Developer interested in video games, SciFi, music, and art.
  footer:
    copyright: "Content &copy; 2013 - present by <a href=\"https://kevingimbel.com/about\">Kevin Gimbel</a>"
    description: |
      <small>This website is build with <a href="https://gohugo.io/" title="Learn more about Hugo, a static site generator">Hugo</a>, the source code is hosted on <a href="https://github.com/kevingimbel/kevingimbel.com" title="View the source code of this website">GitHub</a>. Hosted on <a href="https://www.netlify.com/">Netlify</a>. <a href="/imprint/" title="Legal information">Imprint</a></small>
    mastodon: |
      <small>Follow me on Mastodon <a rel="me" href="https://bullgit.party/@kevin">@kevin@bullgit.party</a></small>

  shortcodes:
    codepen:
      user: "kevingimbel"
      preview: false
      editable: true